"use server";

import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { createServiceRoleClient } from "@/lib/supabase/service";
import { invalidateTaxonomyCache } from "@/lib/taxonomy";

type TaxonomyKind = "item_types" | "rooms" | "styles" | "materials" | "colors";

const VALID_KINDS: TaxonomyKind[] = [
  "item_types",
  "rooms",
  "styles",
  "materials",
  "colors",
];

function slugify(input: string): string {
  // Keep it dumb-simple: lowercase ASCII + digits + underscores.
  // Operators typing Chinese labels get an autogenerated pinyin-ish slug
  // only if they type ASCII; otherwise they must provide their own slug.
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function kindFromForm(fd: FormData): TaxonomyKind {
  const raw = fd.get("kind")?.toString() ?? "";
  if (!(VALID_KINDS as string[]).includes(raw)) {
    throw new Error(`invalid kind: ${raw}`);
  }
  return raw as TaxonomyKind;
}

export async function addTaxonomyItem(fd: FormData): Promise<void> {
  const kind = kindFromForm(fd);
  const label = fd.get("label_zh")?.toString().trim() ?? "";
  const slugRaw = fd.get("slug")?.toString().trim() ?? "";
  const hex = fd.get("hex")?.toString().trim() ?? "";

  if (!label) {
    redirect(`/admin/taxonomy?err=label&kind=${kind}`);
  }

  const slug = slugRaw || slugify(label);
  if (!slug || !/^[a-z0-9_]+$/.test(slug)) {
    redirect(`/admin/taxonomy?err=slug&kind=${kind}`);
  }

  const supabase = createServiceRoleClient();

  if (kind === "colors") {
    if (!/^#[0-9A-Fa-f]{6}$/.test(hex)) {
      redirect(`/admin/taxonomy?err=hex&kind=${kind}`);
    }
    const { error } = await supabase
      .from("colors")
      .insert({ slug, label_zh: label, hex });
    if (error) {
      redirect(
        `/admin/taxonomy?err=db&kind=${kind}&msg=${encodeURIComponent(error.message)}`,
      );
    }
  } else {
    const { error } = await supabase
      .from(kind)
      .insert({ slug, label_zh: label });
    if (error) {
      redirect(
        `/admin/taxonomy?err=db&kind=${kind}&msg=${encodeURIComponent(error.message)}`,
      );
    }
  }

  invalidateTaxonomyCache();
  revalidatePath("/admin/taxonomy");
  revalidatePath("/admin/products/new");
  revalidatePath("/");
  redirect(`/admin/taxonomy?added=${kind}`);
}

export async function deleteTaxonomyItem(fd: FormData): Promise<void> {
  const kind = kindFromForm(fd);
  const slug = fd.get("slug")?.toString() ?? "";
  if (!slug) return;

  const supabase = createServiceRoleClient();
  const { error } = await supabase.from(kind).delete().eq("slug", slug);
  if (error) {
    redirect(
      `/admin/taxonomy?err=db&kind=${kind}&msg=${encodeURIComponent(error.message)}`,
    );
  }

  invalidateTaxonomyCache();
  revalidatePath("/admin/taxonomy");
  revalidatePath("/admin/products/new");
  revalidatePath("/");
  redirect(`/admin/taxonomy?deleted=${kind}`);
}
