/**
 * Auto-export the scene-placement rules to docs/scene-rules.md — the SINGLE
 * human-readable mirror of config/mounting-scene-rules.ts. Regenerated by the
 * `prebuild` npm hook on every `npm run build`, so the doc can never drift from
 * the config. DO NOT hand-edit docs/scene-rules.md — edit the config and
 * rebuild (or run `npm run scene-rules:export`).
 *
 * Pure config → markdown. No DB, no network, no OpenAI.
 */
import { writeFileSync } from "node:fs";
import {
  MOUNTING_SCENE_RULES,
  ITEM_TYPE_SCENE_RULES,
  SUBTYPE_IMPLIES_MOUNTING,
} from "../config/mounting-scene-rules";
import {
  SCENE_PALETTE_POOLS,
  LIVING_SCENES,
  KITCHEN_SCENES,
  SCENE_PROP_RULES,
} from "../config/scene-style-rules";

const PALETTE_LABELS: Record<string, string> = {
  warm: "白瓷 / 浅色产品(需最散,~9成马桶白瓷)",
  cool: "深色 / 金属产品",
  luxury: "金 / 黄铜产品",
  neutral: "彩色产品",
};

const DOC = "docs/scene-rules.md";
const L: string[] = [];

L.push("# 场景摆位规则(自动导出 — 请勿手工编辑)");
L.push("");
L.push(
  "> 由 `config/mounting-scene-rules.ts` 经 `scripts/export-scene-rules.ts` 自动生成" +
    "(`prebuild` 钩子,每次 `npm run build` 重跑)。**改规则请改 config 后重建 —— 手工改这份会被覆盖。**",
);
L.push("");
L.push(
  "场景 prompt 按固定顺序注入三段:**① mounting 安装约束 → ② item_type 摆位规则 → ③ 真实尺寸**。" +
    "缺 mounting(无法判定安装方式)或缺尺寸(任一轴缺失)→ **拦截不生成**(禁止 AI 猜)。",
);
L.push("");

L.push(`## ① Mounting 安装规则(${Object.keys(MOUNTING_SCENE_RULES).length} 条)`);
L.push("");
L.push("键 = `products.attributes.mounting` 的真实值。给一个无产品使用的值加规则不会有任何效果,直到有产品用它。");
L.push("");
for (const [k, v] of Object.entries(MOUNTING_SCENE_RULES)) {
  L.push(`### \`${k}\``);
  L.push("");
  L.push(v);
  L.push("");
}

L.push(`## ② Item_type 摆位规则(${Object.keys(ITEM_TYPE_SCENE_RULES).length} 条)`);
L.push("");
L.push(
  "键 = `products.item_type` 的真实值。**无条目的类别不注入、不报错** —— 机制对所有类别就绪," +
    "规则内容按 Jym 的节奏逐类补,不预造。",
);
L.push("");
for (const [k, v] of Object.entries(ITEM_TYPE_SCENE_RULES)) {
  L.push(`### \`${k}\``);
  L.push("");
  L.push(v);
  L.push("");
}

L.push(`## ③ 背景色调池(材质 → 色调池,每次从池随机抽一个)`);
L.push("");
L.push(
  "白瓷池刻意多样(暖木 / 冷灰水泥 / 深色地板 / 水磨石 / 浅彩墙),让一页白马桶不再是同一种暖米色。" +
    "抽签按产品 id 稳定(同批产品散开),Regenerate 时换一个。",
);
L.push("");
for (const [tone, pool] of Object.entries(SCENE_PALETTE_POOLS)) {
  L.push(`### \`${tone}\` — ${PALETTE_LABELS[tone] ?? tone}(${pool.length} 个)`);
  L.push("");
  for (const s of pool) L.push(`- ${s}`);
  L.push("");
}
L.push("**客厅场景(sofa 等,每材质一个):**");
L.push("");
for (const [tone, s] of Object.entries(LIVING_SCENES)) L.push(`- \`${tone}\`: ${s}`);
L.push("");
L.push(`**厨房场景(range_hood,${KITCHEN_SCENES.length} 个):**`);
L.push("");
for (const s of KITCHEN_SCENES) L.push(`- ${s}`);
L.push("");

L.push(`## ④ 东南亚背景道具层(item_type → 道具)`);
L.push("");
L.push(
  "卫生间场景注入真实东南亚配件指引;若库内有对应 `referenceItemTypes` 的已上传产品," +
    "取其白底图喂给模型作风格参照(所引用产品 id 会被记录,作未来「场景中的其他产品」链接的数据基础)。" +
    "库内无对应配件 → 降级纯文字,不报错。道具永远是配角,不抢镜、不遮挡主产品。",
);
L.push("");
for (const [it, rule] of Object.entries(SCENE_PROP_RULES)) {
  L.push(`### \`${it}\``);
  L.push("");
  L.push(`- 指引:${rule.guidance}`);
  L.push(`- 参照 item_types:${rule.referenceItemTypes.map((t) => `\`${t}\``).join(", ")}`);
  L.push("");
}

L.push(
  `## Subtype → mounting 兜底映射(${Object.keys(SUBTYPE_IMPLIES_MOUNTING).length} 条)`,
);
L.push("");
L.push("产品无显式 `attributes.mounting` 时,用 `subtype_slug` 推断 mounting。");
L.push("");
L.push("| subtype_slug | ⇒ mounting |");
L.push("| --- | --- |");
for (const [k, v] of Object.entries(SUBTYPE_IMPLIES_MOUNTING)) {
  L.push(`| \`${k}\` | \`${v}\` |`);
}
L.push("");

writeFileSync(DOC, L.join("\n"));
console.log(`✓ wrote ${DOC} (${Object.keys(MOUNTING_SCENE_RULES).length} mounting · ${Object.keys(ITEM_TYPE_SCENE_RULES).length} item_type rules)`);
