/**
 * Auto-export the scene-placement rules to docs/scene-rules.md — the SINGLE
 * human-readable mirror of config/mounting-scene-rules.ts. Regenerated by the
 * `prebuild` npm hook on every `npm run build`, so the doc can never drift from
 * the config. DO NOT hand-edit docs/scene-rules.md — edit the config and
 * rebuild (or run `npm run scene-rules:export`).
 *
 * Pure config → markdown. No DB, no network, no OpenAI.
 */
import { writeFileSync } from "node:fs";
import {
  MOUNTING_SCENE_RULES,
  ITEM_TYPE_SCENE_RULES,
  SUBTYPE_IMPLIES_MOUNTING,
  FAUCET_RULES,
  FAUCET_KITCHEN_TOKENS,
} from "../config/mounting-scene-rules";
import {
  SCENE_PALETTE_POOLS,
  LIVING_SCENES,
  KITCHEN_SCENES,
  SCENE_PROP_RULES,
} from "../config/scene-style-rules";

const PALETTE_LABELS: Record<string, string> = {
  warm: "白瓷 / 浅色产品(需最散,~9成马桶白瓷)",
  cool: "深色 / 金属产品",
  luxury: "金 / 黄铜产品",
  neutral: "彩色产品",
};

const DOC = "docs/scene-rules.md";
const L: string[] = [];

L.push("# 场景摆位规则(自动导出 — 请勿手工编辑)");
L.push("");
L.push(
  "> 由 `config/mounting-scene-rules.ts` 经 `scripts/export-scene-rules.ts` 自动生成" +
    "(`prebuild` 钩子,每次 `npm run build` 重跑)。**改规则请改 config 后重建 —— 手工改这份会被覆盖。**",
);
L.push("");
L.push(
  "场景 prompt 按固定顺序注入三段:**① mounting 安装约束 → ② item_type 摆位规则 → ③ 真实尺寸**。" +
    "缺 mounting(无法判定安装方式)或缺尺寸(任一轴缺失)→ **拦截不生成**(禁止 AI 猜)。",
);
L.push("");

L.push(`## ① Mounting 安装规则(${Object.keys(MOUNTING_SCENE_RULES).length} 条)`);
L.push("");
L.push("键 = `products.attributes.mounting` 的真实值。给一个无产品使用的值加规则不会有任何效果,直到有产品用它。");
L.push("");
for (const [k, v] of Object.entries(MOUNTING_SCENE_RULES)) {
  L.push(`### \`${k}\``);
  L.push("");
  L.push(v);
  L.push("");
}

L.push(`## ② Item_type 摆位规则(${Object.keys(ITEM_TYPE_SCENE_RULES).length} 条)`);
L.push("");
L.push(
  "键 = `products.item_type` 的真实值。**无条目的类别不注入、不报错** —— 机制对所有类别就绪," +
    "规则内容按 Jym 的节奏逐类补,不预造。",
);
L.push("");
L.push(
  "> ⚠️ `urinal` / `paper_holder` / `towel_shelf` 三条目前**不是**真实 item_type —— 库里这三类" +
    "产品全是 `item_type='bathroom_equipments'`,靠**产品名关键词**(urinal / paper holder / towel)" +
    "命中(见 `ACCESSORY_NAME_TO_RULE`)。待 taxonomy 拆分出独立 item_type(方案 B)后,按 item_type" +
    "直接命中,名称分类器自动失效。",
);
L.push("");
for (const [k, v] of Object.entries(ITEM_TYPE_SCENE_RULES)) {
  L.push(`### \`${k}\``);
  L.push("");
  L.push(v);
  L.push("");
}

L.push("### `faucet`(无条件盆承接铁律 + 厨房/浴室分流)");
L.push("");
L.push(
  "faucet 不在上面的 map —— 盆承接是**无条件铁律**(不依赖 mounting 命中,mounting 为空也生效)," +
    "并按**产品名**分流:命中 " +
    FAUCET_KITCHEN_TOKENS.map((t) => `\`${t}\``).join(" / ") +
    " → kitchen(不锈钢厨房水槽 + 厨房语境);否则 → basin(陶瓷台盆 + 浴室语境)。承接盆是主产品的**物理承接**," +
    "库内无参照也必须画(不适用「无参照不画」道具铁律);有参照则喂图 + 记 `scene_reference_product_ids`。",
);
L.push("");
for (const kind of ["kitchen", "basin"] as const) {
  L.push(`#### \`faucet · ${kind}\``);
  L.push("");
  L.push(FAUCET_RULES[kind]);
  L.push("");
}

L.push(`## ③ 背景色调池(材质 → 色调池,每次从池随机抽一个)`);
L.push("");
L.push(
  "白瓷池刻意多样(暖木 / 冷灰水泥 / 深色地板 / 水磨石 / 浅彩墙),让一页白马桶不再是同一种暖米色。" +
    "抽签按产品 id 稳定(同批产品散开),Regenerate 时换一个。",
);
L.push("");
for (const [tone, pool] of Object.entries(SCENE_PALETTE_POOLS)) {
  L.push(`### \`${tone}\` — ${PALETTE_LABELS[tone] ?? tone}(${pool.length} 个)`);
  L.push("");
  for (const s of pool) L.push(`- ${s}`);
  L.push("");
}
L.push("**客厅场景(sofa 等,每材质一个):**");
L.push("");
for (const [tone, s] of Object.entries(LIVING_SCENES)) L.push(`- \`${tone}\`: ${s}`);
L.push("");
L.push(`**厨房场景(range_hood,${KITCHEN_SCENES.length} 个):**`);
L.push("");
for (const s of KITCHEN_SCENES) L.push(`- ${s}`);
L.push("");

L.push(`## ④ 背景道具层(item_type → 道具,铁律版)`);
L.push("");
L.push(
  "**铁律(反转 #29):「See it, buy it」—— 场景里出现买不到的道具比空墙更糟。** " +
    "每类道具只有在库内存在该类配件产品**且有白底图**时才注入,并喂其白底图作风格参照;" +
    "**库内没有该配件 → 该道具完全移除(不再有纯文字降级)**。每类道具还按**概率独立抽签**" +
    "(按产品 id 稳定,Regenerate 换种子换组合),同类最多一次,**允许抽出零道具的干净空场景**。" +
    "通用约束:所有物品必须有真实支撑面接触(置台面/挂墙面五金),禁止悬空漂浮。",
);
L.push("");
for (const [it, specs] of Object.entries(SCENE_PROP_RULES)) {
  L.push(`### \`${it}\``);
  L.push("");
  for (const s of specs) {
    L.push(
      `- \`${s.key}\`(概率 ${Math.round(s.probability * 100)}%,参照 \`${s.referenceItemType}\`):${s.label}`,
    );
  }
  L.push("");
}
L.push("### 流程裁定:异形/非常规几何产品");
L.push("");
L.push(
  "安全扶手等异形/非常规几何产品的 AI 场景图**不强求** —— AI 常画歪。**实拍场景图优先**" +
    "(#32 起实拍场景照与 AI 场景图同权过发布闸,人工上传一张真实场景照即可)。",
);
L.push("");

L.push(
  `## Subtype → mounting 兜底映射(${Object.keys(SUBTYPE_IMPLIES_MOUNTING).length} 条)`,
);
L.push("");
L.push("产品无显式 `attributes.mounting` 时,用 `subtype_slug` 推断 mounting。");
L.push("");
L.push("| subtype_slug | ⇒ mounting |");
L.push("| --- | --- |");
for (const [k, v] of Object.entries(SUBTYPE_IMPLIES_MOUNTING)) {
  L.push(`| \`${k}\` | \`${v}\` |`);
}
L.push("");

writeFileSync(DOC, L.join("\n"));
console.log(`✓ wrote ${DOC} (${Object.keys(MOUNTING_SCENE_RULES).length} mounting · ${Object.keys(ITEM_TYPE_SCENE_RULES).length} item_type rules)`);
