/**
 * Auto-export the scene-placement rules to docs/scene-rules.md — the SINGLE
 * human-readable mirror of config/mounting-scene-rules.ts. Regenerated by the
 * `prebuild` npm hook on every `npm run build`, so the doc can never drift from
 * the config. DO NOT hand-edit docs/scene-rules.md — edit the config and
 * rebuild (or run `npm run scene-rules:export`).
 *
 * Pure config → markdown. No DB, no network, no OpenAI.
 */
import { writeFileSync } from "node:fs";
import {
  MOUNTING_SCENE_RULES,
  ITEM_TYPE_SCENE_RULES,
  SUBTYPE_IMPLIES_MOUNTING,
} from "../config/mounting-scene-rules";

const DOC = "docs/scene-rules.md";
const L: string[] = [];

L.push("# 场景摆位规则(自动导出 — 请勿手工编辑)");
L.push("");
L.push(
  "> 由 `config/mounting-scene-rules.ts` 经 `scripts/export-scene-rules.ts` 自动生成" +
    "(`prebuild` 钩子,每次 `npm run build` 重跑)。**改规则请改 config 后重建 —— 手工改这份会被覆盖。**",
);
L.push("");
L.push(
  "场景 prompt 按固定顺序注入三段:**① mounting 安装约束 → ② item_type 摆位规则 → ③ 真实尺寸**。" +
    "缺 mounting(无法判定安装方式)或缺尺寸(任一轴缺失)→ **拦截不生成**(禁止 AI 猜)。",
);
L.push("");

L.push(`## ① Mounting 安装规则(${Object.keys(MOUNTING_SCENE_RULES).length} 条)`);
L.push("");
L.push("键 = `products.attributes.mounting` 的真实值。给一个无产品使用的值加规则不会有任何效果,直到有产品用它。");
L.push("");
for (const [k, v] of Object.entries(MOUNTING_SCENE_RULES)) {
  L.push(`### \`${k}\``);
  L.push("");
  L.push(v);
  L.push("");
}

L.push(`## ② Item_type 摆位规则(${Object.keys(ITEM_TYPE_SCENE_RULES).length} 条)`);
L.push("");
L.push(
  "键 = `products.item_type` 的真实值。**无条目的类别不注入、不报错** —— 机制对所有类别就绪," +
    "规则内容按 Jym 的节奏逐类补,不预造。",
);
L.push("");
for (const [k, v] of Object.entries(ITEM_TYPE_SCENE_RULES)) {
  L.push(`### \`${k}\``);
  L.push("");
  L.push(v);
  L.push("");
}

L.push(
  `## Subtype → mounting 兜底映射(${Object.keys(SUBTYPE_IMPLIES_MOUNTING).length} 条)`,
);
L.push("");
L.push("产品无显式 `attributes.mounting` 时,用 `subtype_slug` 推断 mounting。");
L.push("");
L.push("| subtype_slug | ⇒ mounting |");
L.push("| --- | --- |");
for (const [k, v] of Object.entries(SUBTYPE_IMPLIES_MOUNTING)) {
  L.push(`| \`${k}\` | \`${v}\` |`);
}
L.push("");

writeFileSync(DOC, L.join("\n"));
console.log(`✓ wrote ${DOC} (${Object.keys(MOUNTING_SCENE_RULES).length} mounting · ${Object.keys(ITEM_TYPE_SCENE_RULES).length} item_type rules)`);
